# Generated by Django 3.2.6 on 2021-08-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddinghall',
            name='wedding_hall_list',
        ),
        migrations.DeleteModel(
            name='WeddingHallList',
        ),
    ]
