# Generated by Django 3.2.6 on 2021-08-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_auto_20210813_2045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DishesAndDrinks',
            new_name='DishesAndDrink',
        ),
    ]
