# Generated by Django 3.2.6 on 2021-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0003_rename_dishesanddrinks_dishesanddrink'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
