# Generated by Django 3.2.6 on 2021-08-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0004_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='total_money',
            field=models.BigIntegerField(null=True),
        ),
    ]
