# Generated by Django 3.2.6 on 2021-08-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0005_alter_menu_total_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='bonus_price',
        ),
        migrations.AddField(
            model_name='weddinghall',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weddinghall',
            name='time_wedding',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weddinghall',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='BonusTime',
        ),
    ]
