# Generated by Django 3.2.6 on 2021-08-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0007_service_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dishes_and_drink',
            field=models.ManyToManyField(blank=True, related_name='dishes_and_drink', to='weddings.DishesAndDrink'),
        ),
    ]
