# Generated by Django 3.2.6 on 2021-08-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0008_menu_dishes_and_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishesanddrink',
            name='menus',
        ),
    ]
